receivers:
  jmx:
    jar_path: /otel/opentelemetry-java-contrib-jmx-metrics.jar
    endpoint: service:jmx:rmi:///jndi/rmi://activemq:1099/jmxrmi
    collection_interval: 10s
    target_system: activemq
    resource_attributes:
      service.name: activemq
    log_level: info
    properties:
      otel.jmx.groovy.script: /scripts/activemq-filter.groovy

exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"

service:
  pipelines:
    metrics:
      receivers: [jmx]
      exporters: [prometheus]
